name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - run: pip install uv
      - run: uv sync
      - run: source .venv/bin/activate
      - run: uv run playwright install
      - run: uv run pytest --junit-xml=results.xml tests/test_playwright.py
      - run: uv run locust